### ISSUE TITLE
Launcher flagged as malware

### ISSUE THREAD

**Issue by mogus15** [justkeepquiet/tera-launcher#1]
Since the source code itself is not released it's hard to say if this is a valid catch or not. Backdoors are very popular for crypto mining and placing other potential malware/spyware on a user's machine.

If possible please upload the source for the launcher.

![image](https://user-images.githubusercontent.com/20310233/176549715-456a5b7a-15f6-40fe-88c8-e251dbf1ae42.png)

Virustotal: [https://www.virustotal.com/gui/file/d285e718fa3d472cea4d432ae8135cf20c9ba72bbd751229230b459901fc326f/detection](https://www.virustotal.com/gui/file/d285e718fa3d472cea4d432ae8135cf20c9ba72bbd751229230b459901fc326f/detection)

![image](https://user-images.githubusercontent.com/20310233/176551672-7d759d4f-6ff1-4c6d-b4ef-cb86b570b9e6.png)

**Comment by justkeepquiet** [comment]
This product is owned by HappyTuk (Taiwan localizer of TERA) and has been published without any changes. Unfortunately, we do not have the source codes for this. Therefore, it is unlikely that this problem will be fixed.

**Comment by mogus15** [comment]
Thanks for the reply. Are you aware of any open-source launchers that could be an alternative?

**Comment by justkeepquiet** [comment]
Also you can try Japanese version (TERA JP) of this launcher.
Original link: http://tera.cdn.gameon.jp/tera/launcher/LauncherInstaller_1.0.1.55.exe
Mirror: https://drive.google.com/file/d/1YFDUlyluNv3QwubZ3kAVVd4rzXe02hfj/view?usp=sharing

**Comment by justkeepquiet** [comment]
> Thanks for the reply. Are you aware of any open-source launchers that could be an alternative?

At the moment, the Tera API only supports this launcher.

**Comment by justkeepquiet** [comment]
Results of JP version of launcher: https://www.virustotal.com/gui/file/ad164a5b1f35459ba31d475e92f6a54794d489c2f04060f7ac5a25e8901d4e65?nocache=1

**Comment by mogus15** [comment]
> Results of JP version of launcher: https://www.virustotal.com/gui/file/ad164a5b1f35459ba31d475e92f6a54794d489c2f04060f7ac5a25e8901d4e65?nocache=1

That's an improvement 👍🏾 . Guessing this JP version would not work with your TeraAPI as well?

**Comment by justkeepquiet** [comment]
It will work, we have tested it.

https://github.com/justkeepquiet/tera-launcher/commit/99728cba991283c34223025df80946db60b85579 replaced the binary with the JP version. Please try it.

**Comment by mogus15** [comment]
> It will work, we have tested it.
> 
> [99728cb](https://github.com/justkeepquiet/tera-launcher/commit/99728cba991283c34223025df80946db60b85579) replaced the binary with the JP version. Please try it.

Can confirm JP launcher works with TeraAPI. 

Results of the binary you posted:
- [https://www.virustotal.com/gui/file/4bd8e7055208e819e54ea74fe5d5177084dd3351a5db83b6887ab144e6a4dddb](https://www.virustotal.com/gui/file/4bd8e7055208e819e54ea74fe5d5177084dd3351a5db83b6887ab144e6a4dddb)
- [https://opentip.kaspersky.com/4BD8E7055208E819E54EA74FE5D5177084DD3351A5DB83B6887AB144E6A4DDDB/](https://opentip.kaspersky.com/4BD8E7055208E819E54EA74FE5D5177084DD3351A5DB83B6887AB144E6A4DDDB/)
