### ISSUE TITLE
(Consider) Feature Request headless launcher

### ISSUE THREAD

**Issue by Toastyice** [justkeepquiet/tera-launcher#2]
### **TLDR**: _Please consider adding a headless mode that auto launches into Tera with provided credentials._

I'm currently tring to setup Tera on my steamdeck (Linux). But unfortunately, I can't get the launcher to properly display.
I've played Tera on official servers in the past on Linux without major problems, and I'd love to play on private servers on Linux.

![Screenshot_20220828_111055](https://user-images.githubusercontent.com/26774170/187066695-5cee52e7-7301-4dbc-a95a-662583f1b4dc.png)
Proton 7.0-4 
(Older versions and experimental crash immediately)

**Comment by justkeepquiet** [comment]
This launcher is developed by BHS and we do not have access to its source codes.
You should consider this project: https://www.nuget.org/packages/novadrop-run

In the future, we may add support for alternative launchers in our Tera API.
