### ISSUE TITLE
hi I encountered some issues during debugging, 

### ISSUE THREAD

**Issue by hnzero001** [justkeepquiet/tera-launcher#3]
May I ask if this problem is due to a path setting error? Question 1.Some 404 errors, while others are normal Is there a problem with the env configuration?

Question 2.![QQ图片20230501194527-faq](https://user-images.githubusercontent.com/21352901/235447864-f3171570-19a5-4826-8de0-7f96c1fbf3c5.png)

The login prompts for script errors.

Tks.

**Comment by justkeepquiet** [comment]
Both of your problems are related to the fact that the launcher cannot get static content from the API (images, styles and scripts).

Make sure you have your settings in **.env** set like this:
```
# Enable public directory for static files (needed for Launcher static files).
# Also, this directory can be used to place Launcher and Client update files.
API_PORTAL_PUBLIC_FOLDER_ENABLE=true
```
```
# Set the URL address for placing Client and Launcher updates files.
# If leave it empty, the "/public/patch" root will be used.
API_PORTAL_CLIENT_PATCH_URL=
```
The default API settings are ready to work with this launcher.

**Comment by hnzero001** [comment]
Unable to automatically generate authkey, do you have a supporting website?

![faq2](https://user-images.githubusercontent.com/21352901/235450229-dee98f18-7034-4547-aee2-fa7462d4f303.png)
tks

**Comment by justkeepquiet** [comment]
The **authKey** is generated automatically after successful authorization in the launcher.

**Comment by hnzero001** [comment]
![faq3](https://user-images.githubusercontent.com/21352901/235451467-9d3b456d-b12e-4538-8e7f-f99a4d6061a6.png)
![faq3-1](https://user-images.githubusercontent.com/21352901/235451603-ba45372b-70a4-4691-a07e-2d1d1abf9d15.png)
Is this a mandatory update? I didn't see how to open development mode.

**Comment by justkeepquiet** [comment]
Make sure these https://github.com/justkeepquiet/tera-launcher/tree/master/public/patch files are copied to the `public/patch` directory of tera-api.

**Comment by hnzero001** [comment]
![faq4](https://user-images.githubusercontent.com/21352901/235460463-5600862f-51b5-4ea6-a2aa-14dfa2b51c6f.png)
![faq5](https://user-images.githubusercontent.com/21352901/235460480-a29de232-dead-4c91-a600-c27f4bb459db.png)
Thank you very much for your answer.
Not quite right, in two cases, it's not an address mismatch. The forced update cannot be cancelled. Is it related to other files?

**Comment by justkeepquiet** [comment]
You can set parameter `API_PORTAL_CLIENT_PATCH_NO_CHECK` to `true` in your **.env** config file to disable client updates.

As for file **launcher_info.ini**, it is required to check by the launcher (even if you don't plan to update the launcher).
Make sure the link http://192.168.200.3:818/public/patch/launcher_info.ini works in your browser.

**Comment by justkeepquiet** [comment]
If you do not plan to use a third party host to store updates, leave the `API_PORTAL_CLIENT_PATCH_URL` setting empty.

**Comment by hnzero001** [comment]
I feel a bit dizzy, debugging has been taking too long

![mi1](https://user-images.githubusercontent.com/21352901/235465625-7a841a6b-af25-4649-8c28-1578f9d926cb.png)

**Comment by hnzero001** [comment]
![image](https://user-images.githubusercontent.com/21352901/235467222-bb18b46f-cb4c-45b5-8504-ab60239759f8.png)
loog time

**Comment by justkeepquiet** [comment]
> loog time

Initial packing of the client may take a long time, depending on the performance of your CPU.

**Comment by hnzero001** [comment]
![QQ图片20230502115350faq](https://user-images.githubusercontent.com/21352901/236176517-61cd915c-13bd-46d0-ade8-6ea8e7e496f7.png)
Cannot see registration button
![image](https://user-images.githubusercontent.com/21352901/236177691-9fbe256d-83c0-495a-91d3-fa0275d42948.png)

**Comment by hnzero001** [comment]
![image](https://user-images.githubusercontent.com/21352901/236180361-500e19ba-66ed-44b1-b0c2-69b8016a61ea.png)
![image](https://user-images.githubusercontent.com/21352901/236184466-b71bac50-012c-4afa-8073-92f697800c1f.png)
How many positions need to be set?

**Comment by hnzero001** [comment]
![image](https://user-images.githubusercontent.com/21352901/236184802-5b572d60-fcb3-43a8-ab03-e912b81218f1.png)

**Comment by justkeepquiet** [comment]
You need to configure the recaptcha function keys from https://www.google.com/recaptcha/about/ on this:
```
# Set the site key of the reCAPTCHA service.
API_PORTAL_RECAPTCHA_SITE_KEY=xxx

# Set the secret key of the reCAPTCHA service.
API_PORTAL_RECAPTCHA_SECRET_KEY=xxx
```

Or just disable it by:
```
API_PORTAL_RECAPTCHA_ENABLE=false
```

**Comment by hnzero001** [comment]
![image](https://user-images.githubusercontent.com/21352901/236193577-7e11b56f-1bf1-4bbe-af2f-5eed8757b765.png)
There is no problem with the number of digits I entered in the password.

**Comment by hnzero001** [comment]
![image](https://user-images.githubusercontent.com/21352901/236194654-f3f21cec-f6d9-42a2-83cb-5abb3ae25845.png)
Are there not enough password characters?

**Comment by justkeepquiet** [comment]
You need to use a strong password containing both upper and lower case letters, numbers and a special character.

**Comment by hnzero001** [comment]
ok  tks

**Comment by hnzero001** [comment]
![QQ图片20230505185517](https://user-images.githubusercontent.com/21352901/236453904-5966c18e-a5e9-4642-b406-f2d1b6b53e7c.png)

![2-f微信图片_20230505201315](https://user-images.githubusercontent.com/21352901/236454785-58c1276d-42e9-4531-a62b-d4f526ec1108.png)
1. Has the game account library changed? mysql？
2.Can you tell me how many locations need to fill in the public IP address?

**Comment by justkeepquiet** [comment]
Since this issue is not related to the Launcher or API, you need to go to the [community forum](https://forum.ragezone.com/community/tera.795/) for help.

**Comment by hnzero001** [comment]
![image](https://user-images.githubusercontent.com/21352901/236659777-f227ec5f-3ac3-41ec-999f-724cd0c17934.png)
Is there a problem with what I imported? Page display?

**Comment by hnzero001** [comment]
![image](https://user-images.githubusercontent.com/21352901/236660277-71be6663-b767-403e-a6aa-36984172e019.png)
Can I directly modify this?

**Comment by hnzero001** [comment]
How many positions do these categories need to be changed in the game?
How to send coupons for shopping malls? Gold coins, ID not found
![QQ图片20230507133714](https://user-images.githubusercontent.com/21352901/236670836-8120ec66-540d-41d1-aa48-9ba0faed1aa4.png)

![image](https://user-images.githubusercontent.com/21352901/236667786-fa53ca8a-25af-4b1d-9cef-961eda91d588.png)

**Comment by justkeepquiet** [comment]
How to add an additional language to Tera Shop, Admin panel and API - [read here](https://forum.ragezone.com/threads/tera-api-node-js-shop-and-launcher-with-patcher-for-patch-92-100.1205579/) (How to add new language translation).
